site_name: Webtechnologie 3
copyright: HG 2021
site_author: Bart Barnard en Kayleigh Beard
site_description: 'Studiemateriaal voor de module webtechnologie 3 van de Hanzehogeschool Groningen'
site_url: 'https://hanze-hbo-ict.github.io/webtech3/'
use_directory_urls: false

theme:
  name: 'material'
  palette:
    primary: 'blue grey'
    accent: 'orange'
  icon:
    logo: 'material/library'
  language: 'nl'
  include_sidebar: false
extra_css:
  - css/extra.css

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - markdown.extensions.codehilite:
      guess_lang: False
      linenums: True
  - markdown.extensions.toc:
      permalink: true
      toc_depth: 3
  - markdown.extensions.def_list
  - markdown.extensions.admonition
  - markdown.extensions.footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed

extra_javascript:
  - js/imgs.js
  - js/matjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
#  - with-pdf
  - search
  - mknotebooks:
      execute: false

nav:
  - Introductie: 'index.md'
  - Werkwijze tijdens de practica: 'practicum.md'
  - Memory game: 'memory.md'
  - Hoorcolleges: 'colleges.md'
  - '1. HTML en CSS 1':
    - Inleiding: 'week1/index.md'
    - Practicum: 'week1/practicum.md'
    - Memory: 'week1/memory.md'
  - '2. HTML en CSS 2':
    - Inleiding: 'week2/index.md'
    - Practicum: 'week2/practicum.md'
    - Memory (toetsmoment): 'week2/memory.md'
  - '3. Javascript':
    - Inleiding: 'week3/index.md'
    - Practicum: 'week3/practicum.md'
    - Memory: 'week3/memory.md'
  - '4. Externe bronnen':
    - Inleiding: 'week4/index.md'
    - Practicum: 'week4/practicum.md'
    - Memory (toetsmoment): 'week4/memory.md'
  - '5. Beveiliging en JWT':
    - Inleiding: 'week5/index.md'
    - Practicum: 'week5/practicum.md'
    - Memory (toetsmoment): 'week5/memory.md'
  - '6. MVC en Frameworks 1':
    - Inleiding: 'week6/index.md'
    - Practicum: 'week6/practicum.md'
    - Memory: 'week6/memory.md'
  - '7. MVC en Frameworks 2':
    - Inleiding: 'week7/index.md'
    - Practicum: 'week7/practicum.md'
    - Memory (toetsmoment): 'week7/memory.md'

